name: "Github Action Permissions"
description: "Restrict users who can run an action"
inputs:
  config_file:
    description: "JSON file with permissions"
    required: false
    default: ".devops.config"
  token:
    description: "Github token. Use ${{ secrets.GITHUB_TOKEN }} for the default token."
    required: false
    default: "${{ secrets.GITHUB_TOKEN }}"
runs:
  using: "node16"
  main: "dist/index.js"
